# Generated by Django 4.1.4 on 2022-12-28 08:56

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('dishes', djongo.models.fields.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('link', models.TextField(max_length=255)),
                ('price', models.FloatField(default=[])),
                ('users', djongo.models.fields.JSONField(default=[])),
                ('ingredients', djongo.models.fields.JSONField(default=[])),
                ('store', djongo.models.fields.JSONField(default=[])),
                ('categories', djongo.models.fields.JSONField(default=[])),
            ],
        ),
    ]
